name: efficient_work_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  sizer: ^2.0.15
  google_fonts: ^4.0.4
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
